### PR TITLE
sunlight is inherently more bright than other cases.

### PR DESCRIPTION
**Pull request by Azaezel**
adds a multiplier for higher range variance using the same input value

### CODE REVIEW

**Comment by lukaspj** [comment]
I think this is a bit hacky, I understand why but I'd personally prefer if there were a more transparent solution.
Ideally the brightness range should just change based on the type of light source, since it sound like the issue here is that the input slider GUI does not have a big enough range?

**Comment by Azaezel** [comment]
More a case of on the one hand the values at present being largely arbitrary, and on the other hand avoiding in shader per-pixel calcs for a given light type.

**Comment by dottools** [comment]
Could it not be a configurable value from a variable like  `gWorldAmbientLightFactor` instead of using a magic number `2`?
I forget what Torque's global variable style looks like, so my example global variable is prefixed with a 'g'.

**Comment by Azaezel** [comment]
Sure, but you'd still want to apply that once to the value passed to the shader, not *within* it, multiple times. So the general categories of options are:
A) Multiplier or Sum
B) Higher initial value
Could see going either route, honestly.

**Pull request closed without merging**
