### PR TITLE
Loading from zipped game directories.

### PR DESCRIPTION
**Pull request by OTHGMars**
This PR addresses the issues mentioned in #22.
Also includes fixes for Ogg Vorbis, NavMesh and recursive searching into mounted sub-directories.

### CODE REVIEW

**Comment by chaigler** [comment]
Lots of good stuff in this one! I'm swamped at work this week but will definitely test this over the weekend.

**Comment by Azaezel** [comment]
Initial testing: Dropped https://github.com/Torque3DResources/FPSGameplay into /data/FPSGameplay and got no levels listed for the baseline side effect checking.

**Comment by OTHGMars** [comment]
Additional commits added to fix problems introduced by the initial PR.

**Comment by Azaezel** [comment]
Should be noted, testing found a flaw with forest reading. Mars is looking into it.

**Comment by OTHGMars** [comment]
Closing this Pull Request. It has been replaced by #449.

**Pull request closed without merging**
